Add Org Workspace Members table and various other changes.
turbot/steampipe-plugin-steampipecloud pull request #19
Opened 2022-07-20 13:46 UTC by siddharthaturbot

# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

2022-07-20 15:11 UTC, cbruno10 requested changes
@siddharthaturbot Please see comments, thanks!

2022-07-20 15:11 UTC, cbruno10 commented on CHANGELOG.md
> +  - Renamed column `mod_constraint` to `constraint`
These are breaking changes, what's the reason for making these?

2022-07-20 15:11 UTC, cbruno10 commented on CHANGELOG.md
> +- [steampipecloud_organization_workspace_mod](https://hub.steampipe.io/plugins/turbot/steampipecloud/tables/steampipecloud_workspace_mod)
This format is not consistent with our plugin CHANGELOG format, can you please look at [AWS' CHANGELOG](https://github.com/turbot/steampipe-plugin-aws/blob/main/CHANGELOG.md) as an example and update all `Enhancements` notes?

2022-07-20 15:11 UTC, cbruno10 commented on docs/tables/steampipecloud_organization_member.md
> +### List invited members
Should we add an invited member example, or did you mean to replace? If so, why is the pending members example not required?

2022-07-20 15:11 UTC, cbruno10 commented on docs/tables/steampipecloud_organization_workspace_member.md
> +and
This formatting looks a little inconsistent, can you please run your SQL queries in this file through the formatter mentioned in https://steampipe.io/docs/develop/table-docs-standards#style-conventions-1?

2022-07-20 15:11 UTC, cbruno10 commented on go.mod
> +	github.com/turbot/steampipe-cloud-sdk-go v0.1.2
We should note this change in the `Dependencies` section of the CHANGELOG

2022-07-20 15:11 UTC, cbruno10 commented on steampipecloud/table_steampipecloud_organization.go
> +				Transform:   transform.FromCamel(),
Without `FromCamel`, were these values not rendering properly before?

2022-07-20 15:23 UTC, sidr0cker commented on steampipecloud/table_steampipecloud_organization.go
> +				Transform:   transform.FromCamel(),
have not checked, just added the transform for consistency.

2022-07-20 15:25 UTC, cbruno10 commented on steampipecloud/table_steampipecloud_organization.go
> +				Transform:   transform.FromCamel(),
Can you please see if we need it? We shouldn't add unnecessary transforms

2022-07-20 15:28 UTC, cbruno10 commented on CHANGELOG.md
> +  - Renamed column `mod_constraint` to `constraint`
So is the response data different then? The transform looks the same, so do we get the correct value back for that column now? For instance, if the response field is now called `Constraint` and was previously `ModConstraint`, our transform wouldn't work anymore.

2022-07-20 18:53 UTC, cbruno10 requested changes
Please see suggestions and please fix any lint errors. Also as discussed, please remove breaking column changes for now, we should revisit these and do a sweep across all tables to see if there are any column names we want to make consistent with the API/TF provider.

2022-07-20 18:53 UTC, cbruno10 commented on CHANGELOG.md
> +- Upgraded [steampipe-cloud-sdk-go](https://github.com/turbot/steampipe-cloud-sdk-go/blob/main/CHANGELOG.md#012-2022-07-19) to v0.1.2 ([#19](https://github.com/turbot/steampipe-plugin-steampipecloud/
Can you please update this note to use the same language that we use in other `Dependencies` section, e.g., https://github.com/turbot/steampipe-plugin-oci/blob/main/CHANGELOG.md#v0160-2022-07-14?

2022-07-20 18:53 UTC, cbruno10 commented on CHANGELOG.md
> +- New table added
```suggestion
- New tables added
```

2022-07-20 18:53 UTC, cbruno10 commented on steampipecloud/table_steampipecloud_organization_member.go
>  	var err error
@siddharthaturbot Can you please fix this lint error?

```
steampipecloud/table_steampipecloud_organization_member.go#L127
S1021: should merge variable declaration with assignment on next line (gosimple)
```

2022-07-21 01:04 UTC, cbruno10 approved these changes

2022-07-21 01:06 UTC, merged