Add new table to capture workspace snapshot information.
turbot/steampipe-plugin-steampipecloud pull request #22
Opened 2022-08-08 07:44 UTC by siddharthaturbot

# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

2022-08-08 12:29 UTC, cbruno10 requested changes
@siddharthaturbot Please see my comment regarding commented out code + the linting errors, it seems like some typechecks are failing. Once those are resolved, I'll have another look, thanks!

2022-08-08 12:29 UTC, cbruno10 commented on steampipecloud/connection_config.go
> +	// tr := &http.Transport{
Do we need to leave in commented code (here and in other places?)

2022-08-18 07:03 UTC, LalitLab commented on steampipecloud/connection_config.go
> +		return nil, errors.New("'host' must be set in the connection configuration. Edit your connection configuration file and then restart Steampipe")
Is this change needed?
We must point the host to `"https://cloud.steampipe.io"` by default.


Earlier
```
⚡ steampipe query                      
Welcome to Steampipe v0.17.0-alpha.5
For more information, type .help
> select * from steampipecloud.steampipecloud_workspace
+-------------+-----------------+------------+.......
| id          | workspace_state | handle     | .......
+-------------+-----------------+------------+.......
| w_c8g...6kg | running         | test1      |.......
| w_cb...feg  | running         | testorgdev |.......
| w_c...6j0   | running         | bose       |.......
+------------------------+-----------------+.......

```

Now
```
select * from steampipecloud.steampipecloud_workspace_snapshot
Error: 'host' must be set in the connection configuration. Edit your connection configuration file and then restart Steampipe (SQLSTATE HV000)
> .quit
```

2022-08-19 12:02 UTC, cbruno10 requested changes
@siddharthaturbot Please see comment, thanks!

2022-08-19 12:02 UTC, cbruno10 commented on steampipecloud/table_steampipecloud_workspace_snapshot.go
> +	// If query_where is passed in the query, that takes precedence
@siddharthaturbot In other tables we take this approach, but moving forward we're changing so `query_where` should be combined with the other quals instead.

Are there other tables in this plugin where we have an explicit filter column, and if so, do you know how those tables behave?

2022-08-19 12:16 UTC, cbruno10 commented on steampipecloud/table_steampipecloud_workspace_snapshot.go
> +	// If query_where is passed in the query, that takes precedence
Ok thanks @siddharthaturbot , can you please make the change then to make the query concat with other quals' filters?

2022-08-22 18:50 UTC, cbruno10 commented on steampipecloud/connection_config.go
> +		parsedURL, parseErr := url.Parse(host)
@siddharthaturbot Was there a specific scenario that prompted this change? I couldn't find anything in the PR description or comments about it.

2022-08-22 19:25 UTC, cbruno10 approved these changes

2022-08-22 19:25 UTC, merged